// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lafysstpyiejevhrlmzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZnlzc3RweWllamV2aHJsbXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTcxOTEsImV4cCI6MjA1MzQzMzE5MX0.LhJEo_mRAAqgWE1j-MAAo9mL7y0DfrKNB1t1oGzzWk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);